spring:
  jpa:
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://80.78.241.18:5432/library
    username: libraryAdmin
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
upload:
  path: /static/uploads/